[package]
name = "yamlate"
version = "0.1.0"
authors = ["Darin Minamoto <darinm223@gmail.com>"]

[dependencies]
yaml-rust = "*"
lazy_static = "*"
num = "*"
libc = "*"
clippy = { version = "*", optional = true }

[features]
default = []

[lib]
crate-type = ["dylib"]
